server {
    listen __PORT__;
    server_name _;

    root __FRONTEND_ROOT__;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;
    }
}
